# First Stage: Build the JAR
FROM eclipse-temurin:23-jdk AS build
WORKDIR /app

# Copy only necessary files for dependency caching
COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .
RUN chmod +x mvnw && ./mvnw dependency:go-offline

# Copy the rest of the project and build
COPY . .
RUN ./mvnw clean package -DskipTests

# Second Stage: Run the JAR in a Lightweight JRE Image
FROM eclipse-temurin:23-jre
WORKDIR /app

# Copy the built JAR from the first stage
COPY --from=build /app/target/discoveryserver-0.0.1-SNAPSHOT.jar app.jar

# Expose the Eureka Server port
EXPOSE 8761

# Run the application
ENTRYPOINT ["java", "-jar", "app.jar"]

HEALTHCHECK --interval=10s --retries=5 --start-period=5s --timeout=10s CMD wget --no-verbose --tries=1 --spider localhost:8761/actuator/health || exit 1
