# Stage 1: Build the JAR using Maven
FROM eclipse-temurin:23-jdk AS build
WORKDIR /app

# Copy only necessary files for dependency caching
COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .
RUN chmod +x mvnw && ./mvnw dependency:go-offline

# Copy the rest of the project and build
COPY . .
RUN ./mvnw clean package -DskipTests

# Stage 2: Run the JAR in a lightweight JRE image
FROM eclipse-temurin:23-jre
WORKDIR /app

# Copy the built JAR from the first stage
COPY --from=build /app/target/configserver-0.0.1-SNAPSHOT.jar app.jar

# Expose Config Server port
EXPOSE 8888

# Run the application
ENTRYPOINT ["java", "-jar", "app.jar"]

HEALTHCHECK --interval=10s --retries=5 --start-period=5s --timeout=10s CMD wget --no-verbose --tries=1 --spider localhost:8888/actuator/health || exit 1
